name: バグ報告
description: バグの報告
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: バグの概要
      description: 発生しているバグの概要
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 再現手順
      description: バグを再現する手順
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: 期待する動作
      description: 本来どう動作すべきか
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: 実際の動作
      description: 実際にどう動作したか
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: 環境
      description: OS、ブラウザ等
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: 補足情報
      description: スクリーンショット等
    validations:
      required: false
